global:
  scrape_interval: 5s
scrape_configs:
  - job_name: brewslot
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:8081', 'payment-service:8082', 'loyalty-service:8083', 'settlement-service:8084']
